spring.application.name=marketplace
server.port=8080

spring.datasource.url=jdbc:h2:file:./data/marketplace
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration-ms=86400000
server.max-http-header-size=16KB